version: '3'
services:
  backend:
    container_name: pantry_chef
    build:
      context: .
      dockerfile: Dockerfile
    command: poetry run uvicorn pantry_chef.main:app --host 0.0.0.0 --port 8000 --reload --reload-dir /pantry-chef-backend
    volumes:
      - ./pantry_chef:/pantry-chef-backend/pantry_chef
    environment:
      - PYTHONPATH=.
      - WATCH_FILES=True
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - pantry_chef_network

  db:
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pantry_chef_network



volumes:
  postgres_data:

networks:
  pantry_chef_network:
    external: false
